replicaCount: 2

image:
  repository: nehoraiiii/flask-aws-monitor
  pullPolicy: Always
  tag: "latest"

env:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  
service:
  type: LoadBalancer
  port: 80
  targetPort: 5001

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"